on:
  workflow_dispatch:
  pull_request:
    types: [opened]


jobs:
  test-giphy-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Invoke Giphy PR Comment Docker Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          giphy-api-key: ${{ secrets.GIPHY_API_KEY }}

      - name: Invoke Giphy PR Comment Javascript Action
        uses: snehakarale/js-custom-action-pr@1.0.2-alpha
